### ISSUE TITLE
Regressions after big merge

### ISSUE THREAD

**Issue by marcoesposito1988** [CentroEPiaggio/kuka-lwr#51]
I finally managed to start looking at the Merge in detail. I am going to signal my doubts/questions here (WIP):

single_lwr.launch:
- [ ] why was the IP changed from 192.168.0.20 to 192.168.0.10? Is this necessary?
- [ ] the functionality to add controllers in a stopped state has been removed. Was this intentional?

gravity compensation controller docs:
- [ ] should be updated (the new explicit controller does not require the ros_monitor script any more, and also works in T2 and auto modes)

**Comment by carlosjoserg** [comment]
@marcoesposito1988, hope you enjoyed holidays too. Quick answers, since I'll get back to work next week:

> why was the IP changed from 192.168.0.20 to 192.168.0.10? Is this necessary?

No, not really, it is an arg anyway. I suppose I was working with the other robot while testing and changed this for brevity and remained (we have 10 and 20 for the right and left arm)

> the functionality to add controllers in a stopped state has been removed. Was this intentional?

It's still there, [line 18](https://github.com/CentroEPiaggio/kuka-lwr/blob/master/single_lwr_example/single_lwr_launch/launch/single_lwr.launch#L18) and [line 105](https://github.com/CentroEPiaggio/kuka-lwr/blob/master/single_lwr_example/single_lwr_launch/launch/single_lwr.launch#L105), right?

> should be updated (the new explicit controller does not require the ros_monitor script any more, and also works in T2 and auto modes)

YES, have you tried it yet? Switching back to trajectory sometimes stopped the robot in my case.
